# Generated by Django 3.2.9 on 2021-11-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendenceHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='att_string',
            field=models.CharField(max_length=365),
        ),
    ]
