# Generated by Django 3.2.9 on 2021-11-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='attendence_string',
        ),
    ]
